#ifndef __HARDWARE_H__
#define __HARDWARE_H__

// IO defines
DEFINE_IO(A1,PORTC,4)
DEFINE_IO(B1,PORTC,5)
DEFINE_IO(C1,PORTB,5)
DEFINE_IO(D1,PORTC,0)
DEFINE_IO(E1,PORTC,1)
DEFINE_IO(F1,PORTC,2)
DEFINE_IO(G1,PORTC,3)
DEFINE_IO(A2,PORTD,3)
DEFINE_IO(B2,PORTD,4)
DEFINE_IO(C2,PORTD,5)
DEFINE_IO(D2,PORTB,1)
DEFINE_IO(E2,PORTB,4)
DEFINE_IO(F2,PORTD,2)
DEFINE_IO(G2,PORTD,6)

DEFINE_IO(BTN1,PORTD,7)
DEFINE_IO(BTN2,PORTB,2)

DEFINE_IO(LED_GREEN,PORTB,3)
DEFINE_IO(LED_RED,PORTB,7)

DEFINE_IO(TX,PORTD,1)
DEFINE_IO(RX,PORTD,0)

DEFINE_IO(SWITCH,PORTB,6)

// Settings
#define BTN_LEFT  1
#define BTN_RIGHT 0

#define TEMP_START 50
#define TEMP_MAX 90
#define TEMP_MIN 10

// Utils
#define LED_RED_ON IO_HIGH(LED_RED)
#define LED_RED_OFF IO_LOW(LED_RED)

#define LED_GREEN_ON IO_HIGH(LED_GREEN)
#define LED_GREEN_OFF IO_LOW(LED_GREEN)

#define SWITCH_ON IO_HIGH(SWITCH)
#define SWITCH_OFF IO_LOW(SWITCH)

#endif
